project:
  type: website
  output-dir: docs

website:
  title: "Spotify Wrapped 2024 en R"             
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: imagenes/spotifylogo.png
    width: 300 
    background: "#1db954"    
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo individual"  
        href: my_trabajo_bigdata.html   
      - icon: github
        href: https://github.com/siwilin  
      - icon: envelope
        url: "mailto:<almancar@alumni.uv.es>"
  page-footer:
    border: true
    background: "#1db954"
    left: "2024, Carlos Eduardo Albornoz Manzano"
    center: "Programación y Manejo de Datos con R"
    right:
      - icon: github
        href: https://github.com/siwilin    
      - icon: envelope
        url: "mailto:almancar@alumni.uv.es"           

format:
  html:
    theme: minty         
    mainfont: monospace
    highlight-style: a11y   
    page-layout: full
    css: ./assets/my_styles.css 
    backgroundcolor: "#dcdcdc"

#- para incluir el logo de la UV en la pestaña del navegador
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "imagenes/uv.jpeg" />
     
#- hace el rendered documento (.html) autocontenido  
embed-resources: true  
#- anchor sections (links en las secciones del rendered document)
anchor-sections: true

toc: true
toc-depth: 3
toc-location: left    
toc-title: Tabla de contenidos

other-links:
  - text: Web del curso
    href: https://perezp44.github.io/intro-ds-24-25-web/
  - text: Trabajos de mis compañeros
    href: https://perezp44.github.io/intro-ds-24-25-web/05-trabajos-estudiantes.html 
  - text: Repo del trabajo
    href: https://github.com/siwilin/trabajo_bigdata
  


#- hace que los links se abren en pestañas nuevas
link-external-newwindow: true 

#- Cross-references
crossref:
  fig-title: Gráfico  # (default is "Figure")
  tbl-title: Tabla    # (default is "Table")
  #title-delim: —     # (default is ":")

#- Posicion de los fig-captions
fig-cap-location: bottom

#- opciones para las imágenes hechas con código   
#fig-height: 5
#fig-width: 5
fig-format: png
fig-dpi: 300


#- opciones para los chunks de código --
code-copy: true
code-overflow: wrap   
code-fold: show
code-line-numbers: true

#- embeed the source document
code-tools: true
code-link: true

# Default execute options
execute:
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
  echo: true
  eval: true
  message: false
  warning: false

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  

editor_options: 
  chunk_output_type: console

license: CC BY

lang: es  #- castellano {es, en}
language: assets/_my_language-es.yml
